[trello.com/c/yd3JjZ1f] feat: add chinese localization
Adamant-im/adamant-iOS pull request #415
Opened 2024-01-10 09:30 UTC by StanislavDevIOS

2024-01-11 15:51 UTC, adamant-al requested changes
- Next time check such mistakes yourself
- Now look through if in-message variables are fine
- Next time ask a translator don't translate comments in `/* .. */`

2024-01-11 15:51 UTC, adamant-al commented on CommonKit/Sources/CommonKit/Assets/Localization/zh.lproj/Localizable.strings
> +"Contribute.Section.Rate" = "在app Store中对应用进行评分";
```suggestion
"Contribute.Section.Rate" = "在App Store中对应用进行评分";
```

2024-01-11 15:51 UTC, adamant-al commented on CommonKit/Sources/CommonKit/Assets/Localization/zh.lproj/Localizable.strings
> +"About.Row.Whitepaper.Url" = "https://adamant.im/whitepaper/adamant-whitepaper-en.pdf";
```suggestion
"About.Row.Whitepaper.Url" = "https://adamant.im/whitepaper/adamant-whitepaper-cn.pdf";
```

2024-01-11 15:51 UTC, adamant-al commented on CommonKit/Sources/CommonKit/Assets/Localization/zh.lproj/Localizable.strings
> +"About.Row.Adamant" = "Adamant";
```suggestion
"About.Row.Adamant" = "ADAMANT";
```

2024-01-11 15:51 UTC, adamant-al commented on CommonKit/Sources/CommonKit/Assets/Localization/zh.lproj/Localizable.strings
> +"AccountTab.Wallets.adamant_wallet" = "adamant钱包";
```suggestion
"AccountTab.Wallets.adamant_wallet" = "ADAMANT钱包";
```

2024-01-11 15:51 UTC, adamant-al commented on CommonKit/Sources/CommonKit/Assets/Localization/zh.lproj/Localizable.strings
> +"AccountTab.Wallets.lisk_vallet" = "lisk钱包";
```suggestion
"AccountTab.Wallets.lisk_vallet" = "Lisk钱包";
```

2024-01-11 15:51 UTC, adamant-al commented on CommonKit/Sources/CommonKit/Assets/Localization/zh.lproj/Localizable.strings
> +"Chats.WelcomeMessage" = "ADAMANT是一个真正的区块链信使，独立于政府、企业甚至开发商。这是由于去中心化的网络基础设施，完全开源，由用户运行。这就是为什么每一个动作，包括发送消息或保存联系人姓名，都有0.001 ADM的网络费用。\n\nBlockchain提供了卓越的安全性和隐私，这是典型的P2P和c集中的信使。此外，区块链提供了新的可能性。您可以在聊天中存储和传
```suggestion
"Chats.WelcomeMessage" = "ADAMANT是一个真正的区块链信使，独立于政府、企业甚至开发商。这是由于去中心化的网络基础设施，完全开源，由用户运行。这就是为什么每一个动作，包括发送消息或保存联系人姓名，都有0.001 ADM的网络费用。\n\nBlockchain提供了卓越的安全性和隐私，这是典型的P2P和c集中的信使。此外，区块链提供了新的可能性。您可以在聊天中存储和传输密码，并完全控制您的私钥，使用ADAMANT作为2FA等。\n\nADAMANT中，没有人可以控制、阻止、停用、限制或审查帐户。用户对内容、消息、媒体以及使用Messenger的目标和意图承担全部责任。\n\n请注意，您的安全性和匿名性取决于您。不要关注你收到的链接，否则你的IP可能会被泄露。在设备上设置密码。了解有关安全性和匿名性的更多信息，请访问https://adamant.im/staysecured/.\n\n请确保已保存此帐户的密码短语--注销并再次登录。把你的通行证短语也写在纸上。只有**您对通行证短语的安全负责**。它无法恢复。如果其他人得到了它，你的代币就会被盗，信件也会被读取。把这个问题看得最重要，就好像你钱包里的代币在一段时间内会花费10亿美元一样。\n\n若要立即开始发送消息，请在\"帐户\"选项卡上**获得免费欢迎令牌**。然后创建新聊天并输入您朋友的ADM地址。建议您亲自分享ADM地址，不要使用其他信使。";
```

2024-01-11 15:51 UTC, adamant-al commented on CommonKit/Sources/CommonKit/Assets/Localization/zh.lproj/Localizable.strings
> +"Chats.Exchange.WellomeMessage" = "嗨！😊 我是你的交换机器人。我即时匿名操作。键入* */help**看看我能做些什么。我要求的费用比我的机器人同伴高，所以我建议你以有竞争力的费用建立自己的机器人。ℹ️ 你可以在ADAMANT博客上了解更多信息。我非常可靠，但如果您有任何问题，请在这里留言U6386412615727665758。";
```suggestion
"Chats.Exchange.WelcomeMessage" = "嗨！😊 我是你的交换机器人。我即时匿名操作。键入* */help**看看我能做些什么。我要求的费用比我的机器人同伴高，所以我建议你以有竞争力的费用建立自己的机器人。ℹ️ 你可以在ADAMANT博客上了解更多信息。我非常可靠，但如果您有任何问题，请在这里留言U6386412615727665758。";
```

2024-01-11 15:51 UTC, adamant-al commented on CommonKit/Sources/CommonKit/Assets/Localization/zh.lproj/Localizable.strings
> +"Chats.Donate.WellomeMessage" = "感谢您的支持，我们开发了去中心化的ADAMANT Messenger——在此聊天中转移ADM、ETH和其他代币。有关其他捐赠钱包，请参阅consided.im。";
```suggestion
"Chats.Donate.WelcomeMessage" = "感谢您的支持，我们开发了去中心化的ADAMANT Messenger——在此聊天中转移ADM、ETH和其他代币。有关其他捐赠钱包，请参阅adamant.im。";
```

2024-01-11 15:51 UTC, adamant-al commented on CommonKit/Sources/CommonKit/Assets/Localization/zh.lproj/Localizable.strings
> +"SecurityPage.Row.Notifications.ModesDescription" = "####通知模式\n\n####禁用\n无通知。\n\n####后台提取\n您的设备会自动提取新消息。没有外部调用。提取由iOS启动，实际时间由操作系统根据电池电量、蜂窝网络、应用程序使用模式等许多因素确定，无法预测。可以是20分钟、6小时，甚至可能是一天。不过，您仍然可以打开应用程序并查看
```suggestion
"SecurityPage.Row.Notifications.ModesDescription" = "####通知模式\n\n####禁用\n无通知。\n\n####后台提取\n您的设备会自动提取新消息。没有外部调用。提取由iOS启动，实际时间由操作系统根据电池电量、蜂窝网络、应用程序使用模式等许多因素确定，无法预测。可以是20分钟、6小时，甚至可能是一天。不过，您仍然可以打开应用程序并查看新消息。\n\n####推送\n ADAMANT通知服务发送到您的设备的通知。在消息发送并获得区块链批准后，您几乎会立即收到通知——延迟几秒钟。但此模式要求您的设备在服务的数据库中注册其设备令牌。设备令牌是安全的，在大多数情况下建议使用此选项。\n\n您可以在ADAMANT的GitHub页面上阅读更多关于设备注册的信息。\n\n";
```

2024-01-11 15:51 UTC, adamant-al commented on CommonKit/Sources/CommonKit/Assets/Localization/zh.lproj/Localizable.strings
> +"SecurityPage.Row.VisitGithub" = "访问Github";
```suggestion
"SecurityPage.Row.VisitGithub" = "访问GitHub";
```

2024-01-11 15:51 UTC, adamant-al commented on CommonKit/Sources/CommonKit/Assets/Localization/zh.lproj/Localizable.strings
> +"WelcomeScene.Description.Slide5" = "项目的源代码[完全开放](https://github.com/Adamant-im/).该应用程序正在开发中，我们不断添加新功能。\\n\n如果您是开发人员，请加入我们的团队。";
```suggestion
"WelcomeScene.Description.Slide5" = "项目的源代码[完全开放](https://github.com/Adamant-im/).该应用程序正在开发中，我们不断添加新功能。\n\n如果您是开发人员，请加入我们的团队。";
```

2024-01-11 15:51 UTC, adamant-al commented on CommonKit/Sources/CommonKit/Assets/Localization/zh.lproj/Localizable.strings
> +"EULA.Text" = "ADAMANT Messenger基于去中心化的区块链技术，因此：\n\n✓ ADAMANT Messenger不容忍令人反感的内容或辱骂用户\n✓ ADAMANT Messenger最初专注于通信的安全性和用户的隐私。\n✓ ADAMANT Messenger始终显示完全开源的代码，许可证为GPL-3.0。源代码可在GitHub:GitHub.com/stend-
```suggestion
"EULA.Text" = "ADAMANT Messenger基于去中心化的区块链技术，因此：\n\n✓ ADAMANT Messenger不容忍令人反感的内容或辱骂用户\n✓ ADAMANT Messenger最初专注于通信的安全性和用户的隐私。\n✓ ADAMANT Messenger始终显示完全开源的代码，许可证为GPL-3.0。源代码可在GitHub:GitHub.com/stend-im上获得。\n✓ ADAMANT Messenger按\"原样\"提供，不提供任何担保。\n✓ 开发人员只是ADAMANT Messenger的贡献者和用户。\n✓ 开发人员不控制用户的任何操作。\n✓ 开发人员在ADAMANT Messenger中没有权限。\n✓ 开发人员不可能禁用或阻止ADAMANT Messenger中的任何帐户。\n✓ 开发人员不可能获得加密密钥或读取任何ADAMANT Messenger用户的通信或其他信息。\n✓ 如果丢失，开发人员不可能恢复对任何用户帐户的访问。用户有责任保护自己的帐户的安全。\n✓ 开发人员不对用户内容、消息、媒体以及使用ADAMANT Messenger的目标和意图负责。\n✓ 开发者不存储用户之间传输的任何信息（消息、多媒体），也不对其在区块链上/中的存储负责。\n✓ 开发者不可能访问，也不对连接到ADAMANT Messenger或通过ADAMANT信使发送的任何资产（包括但不限于：加密货币）负责。\n✓ ADAMANT Messenger利用元数据作为账户之间通信的事实，在其区块链中公开提供。\n✓ 开发者不与任何第三方或外部服务合作提供任何使用数据。\n✓ ADAMANT信使基础设施（区块链节点）属于其用户，由用户运行。\n✓ 开发人员不可能停用、停止或暂停ADAMANT Messenger。开发人员对ADAMANT Messenger的运行不提供任何保证。\n✓ 开发人员不承担与ADAMANT Messenger相关的可能风险、成本和故障。\n✓ ADAMANT Messenger的用户从此对其使用承担全部责任，包括但不限于：区块链和Messenger内应用的其他技术的合法性，使用匿名消息服务，以及其他管辖法律。\n\n通过使用ADAMANT Messenger，您从此接受这些服务条款。";
```

2024-01-15 09:06 UTC, just-software-dev approved these changes

2024-01-15 10:39 UTC, adamant-al approved these changes

2024-01-15 12:44 UTC, merged